isomerpages/moe-peihwaprespri

- _about-pei-hwa/School Staff/Administrative and Support Staff.md
- _about-pei-hwa/School Staff/Teaching Staff 2023 (Form Teachers).md
Need your help to update the school website.
Changes are as follows:
P2/1 : From Mdm Tan Lay Yen to Mrs Emily Chin
P5/2: Add 3rd FT: Mdm Teo Jing Wen
Take out Venesha too
> Form Teacher List - Term 3

- _about-pei-hwa/School Calendar.md
Updated details for School Calendar 2023 Term 3 and 4
> School Calendar 2023 Term 3 and 4

- _about-pei-hwa/Quick Links.md
- _co-curricular-activites/Clubs and Societies/Chinese Culture and Language.md
- _co-curricular-activites/Clubs and Societies/Christian Fellowship.md
- _co-curricular-activites/Clubs and Societies/Drama Club.md
- _co-curricular-activites/Clubs and Societies/ICT Club.md
- _co-curricular-activites/Clubs and Societies/Robotics Club.md
- _co-curricular-activites/Sports and Games/Gymnastics.md
- _co-curricular-activites/Sports and Games/Table Tennis.md
- _co-curricular-activites/Sports and Games/Tchoukball.md
- _co-curricular-activites/Sports and Games/Track and Field.md
- _co-curricular-activites/Sports and Games/Wushu.md
- _co-curricular-activites/Uniformed Groups/Boys' Brigade.md
- _co-curricular-activites/Uniformed Groups/Girls' Brigade.md
- _co-curricular-activites/Visual and Performing Arts/Art & Craft Club.md
- _co-curricular-activites/Visual and Performing Arts/Chinese Dance.md
- _co-curricular-activites/Visual and Performing Arts/Chinese Drums.md
- _co-curricular-activites/Visual and Performing Arts/Choir.md
- _co-curricular-activites/Visual and Performing Arts/Guitar Ensemble.md
- _co-curricular-activites/Visual and Performing Arts/Guzheng Ensemble.md
- _co-curricular-activites/Visual and Performing Arts/Modern Dance.md
CCA Teacher IC Updates for All CCAs request by Kok Yew
> CCA Teacher IC Updates for All CCAs request by Kok Yew

- _co-curricular-activites/Sports and Games/Table Tennis.md
- _co-curricular-activites/Sports and Games/Tchoukball.md
- Table-tennis - Typo for teacher's name - Guo Ting Ting
- Tchoukball - Day of CCA - Mon and Fri
Above amended done
> CCA Updates : Typo Error Amends

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
updated ITQ on website
Document no.	:	MOESCHETQ23003287
Reference no.	:	2023SML17
Title	:	Supply of Instructor(s) for Two-Days Thinkers Today Leaders Tomorrow (TTLT) Leadership Service Camp 2023
Publish date	:	18 Jul 2023
Close date	:	26 Jul 2023 01:00 PM
> GeBIZ: Business opportunity has been published (MOESCHETQ23003287)

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Update on RFQ site page
Document no.	:	MOESCHETQ23003641
Reference no.	:	2024ChoirLine1
Title	:	Supply of instructor for Choir CCA Training Programme in PHPPS from Jan 2024 to Dec 2024, with option to extend from Jan 2025 to Dec 2025
Publish date	:	07 Aug 2023
Close date	:	17 Aug 2023 01:00 PM
Document no.	:	MOESCHETQ23003635
Reference no.	:	2023PELine13
Title	:	Supply of Instructor(s) for P6 Learn to Play Skateboarding Programme
Publish date	:	07 Aug 2023
Close date	:	16 Aug 2023 01:00 PM
> Update on RFQ site page

- _about-pei-hwa/General Information/Announcement.md
Announcement Update: Primary 1 Orientation for 2024 cohort is on 9 Nov 2023 , Thursday.
Requested by Admin Office
> Announcement Update: Primary 1 Orientation for 2024 cohort is on 9 Nov 2023 , Thursday.

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
GeBIZ: Business opportunity has been published (MOESCHETQ23005141) - School Uniform
Document no.	:	MOESCHETQ23005141
Reference no.	:	2024/PHPPS
Agency	:	Ministry of Education – Schools
Title	:	Provision of School Uniform Services in PHPPS from Jan 2024 to Dec 2025, with option to extend from Jan 2026 to Dec 2027
Publish date	:	03 Oct 2023
Close date	:	11 Oct 2023 01:00 PM
> GeBIZ: Business opportunity has been published (MOESCHETQ23005141) - School Uniform

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
- _our-partners/Parents/Parent Volunteers.md
- pages/135th PHPPS Anniversary.md
ITQ Update on CCA Robotics, touckball, track field
> ITQ Update on CCA Robotics, touckball, track field

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
ITQ Update: Edited typo CCA Dates
> ITQ Update: Edited typo CCA Dates

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
RFQ update bookshop closing 6 nov
> RFQ update bookshop closing 6 nov

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Supply of Main & Assistant Instructor for Table Tennis Competitive CCA Training Programme in Pei Hwa Presbyterian Primary School
Supply of Instructor for Table Tennis Recreational CCA Training Programme in Pei Hwa Presbyterian Primary School
> MOESCHETQ23008018 ,  MOESCHETQ23008019

- _about-pei-hwa/Our PHPPS Heritage/PHPPS 135th Anniversary Gift Memorabilia.md
- _about-pei-hwa/School Management Committee.md
- _about-pei-hwa/School Staff/Key Personnel.md
updated info on SMC 
Hi Yusman,
Thanks.  Please remove:
Elder Steven Chan
Elder Lionel Khoo
Dn Sherrin Chua
Ms Yvonne Gan
Remove repeated names
Bring Elder Chew and Rev Goh up the list after the Secretary and Rev Roy Koh down before SLs.
Bring SLs to the bottom of list. Tks
Vincent Tan 
etails
> updated info on SMC details

- _about-pei-hwa/School Management Committee.md
> SMC New Term of Office 1 Jan 2024 to 31 Dec 2026

- _about-pei-hwa/School Management Committee.md
> SMC update 3

- _about-pei-hwa/Our PHPPS Heritage/PHPPS 135th Anniversary Gift Memorabilia.md
jotform link update 2nd order phpps 135 lego
> jotform link update 2nd order phpps 135 lego

- _about-pei-hwa/Quick Links.md
- index.md
> PHPPS GSITE on school website

- _co-curricular-activites/Clubs and Societies/Chinese Culture and Language.md
- _co-curricular-activites/Clubs and Societies/Christian Fellowship.md
- _co-curricular-activites/Clubs and Societies/Drama Club.md
- _co-curricular-activites/Clubs and Societies/ICT Club.md
- _co-curricular-activites/Clubs and Societies/Robotics Club.md
- _co-curricular-activites/Sports and Games/Gymnastics.md
- _co-curricular-activites/Sports and Games/Table Tennis.md
- _co-curricular-activites/Sports and Games/Tchoukball.md
- _co-curricular-activites/Sports and Games/Track and Field.md
- _co-curricular-activites/Sports and Games/Wushu.md
- _co-curricular-activites/Uniformed Groups/Boys' Brigade.md
- _co-curricular-activites/Uniformed Groups/Girls' Brigade.md
- _co-curricular-activites/Visual and Performing Arts/Art & Craft Club.md
- _co-curricular-activites/Visual and Performing Arts/Chinese Dance.md
- _co-curricular-activites/Visual and Performing Arts/Chinese Drums.md
- _co-curricular-activites/Visual and Performing Arts/Choir.md
- _co-curricular-activites/Visual and Performing Arts/Guitar Ensemble.md
- _co-curricular-activites/Visual and Performing Arts/Guzheng Ensemble.md
- _co-curricular-activites/Visual and Performing Arts/Modern Dance.md
CCA Update on venue, teacher ICs, days of each CCa
> CCA Updates from Kok Yew

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
- index.md
> school announcement, ITR

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ24000609
Reference no.	:	2024SML22
Title	:	Peer Support Training for School Peer Supporters (SPS) and CCA Leaders
Publish date	:	01 Feb 2024
Close date	:	16 Feb 2024 01:00 PM
> GeBIZ: Business opportunity has been published (MOESCHETQ24000609)

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
MOESCHETQ24000723
2024PELine4
Ministry of Education - Schools
Supply of Instructor/s for 3 Days 2 Nights Primary 5 Outdoor Education and Team-Building Camp 2024
08 Feb 2024
28 Feb 2024 01:00 PM
Document no.	:	MOESCHETQ24000720
Reference no.	:	2024CLLine37
Title	:	Production of Video Highlights and Photography and Videography services for 7th National Text Recital Competition 2024 Finals and Awards Ceremony
Publish date	:	08 Feb 2024
Close date	:	29 Feb 2024 01:00 PM
> RFQ Updates

- _config.yml
- _data/footer.yml
deleted social media apps urls from main page footer
> deleted social media apps urls

- index.md
> update school annoucements

- _about-pei-hwa/School Staff/Teaching Staff 2024 (Form Teachers).md
- _about-pei-hwa/School Staff/Teaching Staff 2024 (Non Form Teachers).md
as per outlook email
Changes are in yellow as per attached (P4/2 & P5/2) & remove Mr Wong Phuay Hang, Ms Evelyn Wong & Mrs Esther Lee from the Non-FT List.
> Update: Teaching Staff List Term 2 as of 18 March 2024

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
MOESCHETQ24001333  REQUIREMENT SPECIFICATIONS FOR THE DESIGN AND PRODUCTION OF 2024 SCHOOL ANNUAL FOR PEI HWA PRESBYTERIAN PRIMARY SCHOOL
> MOESCHETQ24001333 REQUIREMENT SPECIFICATIONS FOR THE DESIGN AND PRODUCTION OF 2024 SCHOOL ANNUAL FOR PEI HWA PRESBYTERIAN PRIMARY SCHOOL

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Supply of Part Time Office Attendant to Support Office Administration from 1 July 2024 to 30 June 2025 with Option to extend for another one year
> Supply of Part Time Office Attendant to Support Office Administration from 1 July 2024 to 30 June 2025 with Option to extend for another one year

- _about-pei-hwa/School Staff/Administrative and Support Staff.md
- pages/editor ver.md
removed geraldine on staff info eas page
> removed geraldine on staff info eas page

- _about-pei-hwa/General Information/School Rules and Regulations.md
- _about-pei-hwa/Quick Links.md
update to remove quick link  broken link to url PG
> update to remove quick link  broken link to url PG

- _about-pei-hwa/School Staff/Teaching Staff 2024 (Form Teachers).md
- _co-curricular-activites/Sports and Games/Gymnastics.md
- index.md
Updates: remove 135 annoucement, Staff FT Name Updates
> Updates: remove 135 annoucement, Staff FT Name Updates

- index.md
sch annoucements.  sch visitation request by mr tan via whatapps
> sch annoucements.  sch visitation 

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ24003600
Reference no.	:	PERIScienceGarden
Title	:	Design, supply & construction of Science Garden (Including supply of garden elements and outdoor learning spaces)
Publish date	:	26 Aug 2024
Close date	:	25 Sep 2024 01:00 PM
> itq update

- _about-pei-hwa/School Staff/Teaching Staff 2024 (Form Teachers).md
to remove Mr Wong P H from 4TW2? Add him to 2R3 instead.  WEF from today.  Thanks
> yvonne admin office update phuay hang

- _our-partners/Parents/2025 P1 School Books and Uniform Sale.md
- _our-partners/Parents/Feedback Form.md
- _our-partners/Parents/Parents.md
- _our-partners/collection.yml
Parents Page Quick Links Revamp
> Parents Page Quick Links Revamp

- _our-partners/Parents/2025 P1 School Books and Uniform Sale.md
2025 p1 booklist uniform update: alignments
> 2025 p1 booklist uniform update

- _learning-at-pei-hwa/Special Programme/Learning for Life Programme (LLP).md
LLP sitepage  Blue text error change coding to default text
> LLP sitepage Blue text error change coding to default text

- _about-pei-hwa/School Management Committee.md
- _about-pei-hwa/School Staff/Key Personnel.md
- _co-curricular-activites/Sports and Games/Table Tennis.md
- _co-curricular-activites/Visual and Performing Arts/Guitar Ensemble.md
> vpa remove

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
MOESCHETQ24005546	Supply of Instructor for Chinese Culture and Language CCA in PHPPS from 1 Jan 2025 to 31 Dec 2025,with option to extend from 1 Jan 2026 to 31 Dec 2026l	21 Oct 2024	29 Oct 2024 01:00 PM
> MOESCHETQ24005546	

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
> RFQ Table tennis updated 2025

- _our-partners/Parents/Parent Volunteers.md
2nd Jan 2020 to 1st Jan 2021 (both dates inclusive) is 31st May 2025
> PV update details as comment

- _co-curricular-activites/Clubs and Societies/Chinese Culture and Language.md
- _co-curricular-activites/Clubs and Societies/Christian Fellowship.md
- _co-curricular-activites/Uniformed Groups/Boys' Brigade.md
- _co-curricular-activites/Visual and Performing Arts/Choir.md
> CCA Year Photo Removed

- _about-pei-hwa/School Service Providers/Student Care Centre.md
jotform link for SCC application
> jotform link for SCC application 

- _about-pei-hwa/General Information/School Rules and Regulations.md
> 2025 Regulations update following student handbook

- _about-pei-hwa/School Service Providers/School Bus Service.md
- _about-pei-hwa/School Staff/Teaching Staff 2024 (Non Form Teachers).md
admin office bryan reported in
> school bus application 2025 application

- _about-pei-hwa/School Staff/Teaching Staff 2025 (Form Teachers).md
2025 FT staff 2nd edit new editor
> 2025 FT staff 2nd edit new editor

- _about-pei-hwa/School Calendar.md
- _about-pei-hwa/School Staff/Key Personnel.md
school calendar 2025 sem1 update
> school calendar 2025 sem1 update

- _about-pei-hwa/School Staff/Teaching Staff 2025 (Non Form Teachers).md
> email links for staff test1

- _about-pei-hwa/School Staff/Key Personnel.md
> Key Personnel ammends

- _about-pei-hwa/School Calendar.md
school calendar ammends as of 10jan
> school calendar ammends as of 10jan

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
following Invitation To Quote has been published in GeBIZ (https://www.gebiz.gov.sg)
Document no.	:	MOESCHETQ25000321
Reference no.	:	2025SML10
Title	:	Supply of Instructor for Student Leaders' Leadership Camp in Pei Hwa Presbyterian Primary School
Publish date	:	23 Jan 2025
Close date	:	11 Feb 2025 01:00 PM
> GeBIZ: Business opportunity has been published (MOESCHETQ25000321)

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ25000333
Reference no.	:	2025SML7
Title	:	Supply of Instructor for Peer Support Training for Peer Support Leaders & CCA Leaders in Pei Hwa Presbyterian Primary School
Publish date	:	24 Jan 2025
Close date	:	14 Feb 2025 01:00 PM
> GeBIZ: Business opportunity has been published (MOESCHETQ25000333)

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ25000668
Reference no.	:	2025PELine4
Title	:	Supply of Instructors for 3 Days 2 Nights Primary 5 Outdoor Education and Team-Building Camp 2025
Publish date	:	12 Feb 2025
Close date	:	20 Feb 2025 01:00 PM
> RFQ Site page update

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ25000864
Reference no.	:	2025CLLine19
Title	:	Supply of Instructors for Chinese Brush Calligraphy in Pei Hwa Presbyterian Primary School
Publish date	:	24 Feb 2025
Close date	:	04 Mar 2025 01:00 PM
> MOESCHETQ25000864

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
- index.md
Document no.	:	MOESCHERQ25000365
Reference no.	:	MOE24PB-CHN
Title	:	Provision of 5 Days 4 Nights Overseas Immersion Trip for School Staff and Students to Beijing.
Publish date	:	14 Mar 2025
Close date	:	24 Mar 2025 01:00 PM
> RFQ Update in Partners

- _about-pei-hwa/School Bus Advertisement.md
- _about-pei-hwa/School Canteen Advertisement.md
- _about-pei-hwa/School Service Providers/School Bus Service.md
- _about-pei-hwa/School Staff/Teaching Staff 2025 (Non Form Teachers).md
- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
bus service fare, ITQ,  Staff non FT Peirong update.
> admin update

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
> GeBIZ: Business opportunity has been published (MOESCHETQ25001968)Redesign & refurbishment of existing school foyer @ PHPPS

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ25002071
Reference no.	:	2025SMLine15
Title	:	Supply of Instructor(s) for Two-Days Thinkers Today Leaders Tomorrow (TTLT) Leadership Service Camp 2025
Publish date	:	23 Apr 2025
Close date	:	05 May 2025 01:00 PM
> GeBIZ: Business opportunity has been published (MOESCHETQ25002071)

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
Document no.	:	MOESCHETQ25002025
Reference no.	:	2025CLLine31
Title	:	Supply & Delivery of Book Vouchers for 8th National Text Recital Competition
Publish date	:	21 Apr 2025
Close date	:	29 Apr 2025 01:00 PM
> t: GeBIZ: Business opportunity has been published (MOESCHETQ25002025) ITQ for Supply and Delivery of Book Vouchers for National Text Recital

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
</tr>	<tr><td class="tg-q1lf"><span style="color:#282828;background-color:transparent">MOESCHETQ25001968 </span></td>
<td class="tg-q1lf"><span style="color:#282828;background-color:transparent">Redesign &amp; refurbishment of existing school foyer at Pei Hwa Presbyterian Primary School </span></td>
<td class="tg-q1lf"><span style="color:#282828;background-color:transparent">17 Apr 2025 </span></td>
<td class="tg-q1lf"><span style="color:#282828;background-color:transparent">13 May 2025 1:00PM </span></td>
> MOESCHETQ25001968 

- _about-pei-hwa/Quick Links.md
- _our-partners/Parents/Parents.md
Location of Link is available via 
About Pei Hwa >  Quick Links
About Our Partners > Parents > One Stop Links
https://go.gov.sg/phppswaitinglist
> Proposal on putting up quick links on our School Website.

- _our-partners/Invitation To Quote (ITQ) & Request For Quotation (RFQ).md
MOESCHETQ25003512
2026GuzhengLine1
Ministry of Education - Schools
Supply of Instructor for Guzheng Ensemble CCA Training Programme in PHPPS from Jan to Dec 2026, with option to extend from Jan to Dec 2027
06 Aug 2025
14 Aug 2025 01:00 PM
> MOESCHETQ25003512

- _about-pei-hwa/Quick Links.md
- _our-partners/School Alumni/School Alumni.md
VP ask to alumni removal application and HOD quick link update links
> alumni removal application and quick link update links

- _our-partners/Parents/2026 P1 Parents.md
- index.md
> re edit url
